[package]
name = "nx_utils"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
machine-uid = { workspace = true }
