[package]
name = "nx_logger"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
tracing = { workspace = true}
tracing-subscriber = { workspace = true}
colored = { workspace =  true}
