[package]
name = "nx_db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rusqlite = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
fs4 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
