name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main-linux:
    runs-on: ubuntu-latest
    env:
      NX_E2E_CI_CACHE_KEY: e2e-github-linux
      NX_DAEMON: 'true'
      NX_PERF_LOGGING: 'true'
      NX_VERBOSE_LOGGING: 'true'
      NX_NATIVE_LOGGING: 'false'
      NX_E2E_RUN_E2E: 'true'
      NX_CI_EXECUTION_ENV: 'linux'
      NX_CLOUD_DTE_V2: 'true'
      NX_CLOUD_DTE_SUMMARY: 'true'
      NX_CLOUD_NO_TIMEOUTS: 'true'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Master
        run: git fetch origin master:master
        if: ${{ github.event_name == 'pull_request' }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      - name: Install project dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm playwright install --with-deps

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Start CI Run
        run: pnpm nx-cloud start-ci-run --distribute-on="manual" --assignment-rules=".nx/workflows/dynamic-changesets.yaml"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates lsof libvips-dev libglib2.0-dev libgirepository1.0-dev

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check Documentation
        run: pnpm nx documentation
        timeout-minutes: 20

      - name: Close Ci Run
        run: |
          npx nx-cloud complete-ci-run
