name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main-linux:
    runs-on: ubuntu-latest
    env:
      NX_E2E_CI_CACHE_KEY: e2e-github-linux
      NX_DAEMON: 'false'
      NX_PERF_LOGGING: 'true'
      NX_VERBOSE_LOGGING: 'false'
      NX_NATIVE_LOGGING: 'false'
      NX_E2E_RUN_E2E: 'true'
      NX_CI_EXECUTION_ENV: 'linux'
      NX_CLOUD_DTE_V2: 'true'
      NX_CLOUD_DTE_SUMMARY: 'true'
      NX_CLOUD_NO_TIMEOUTS: 'true'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Master
        run: git fetch origin master:master
        if: ${{ github.event_name == 'pull_request' }}

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      - name: Install project dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm playwright install --with-deps

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Calculate Graph (cold)
        run: npx nx show projects

      - name: Extract Nx Perf Timings (warm)
        run: |
          node ./extract-timings.js perf-timings.csv
          echo "################################"
          echo "####### PERF TIMINGS ###########"
          echo "################################"
          echo "  "
          cat perf-timings.csv